export const ADD_NEW_CLUB = 'ADD_NEW_CLUB';
export const DECREMENT_BAG_SIZE = 'DECREMENT_BAG_SIZE';
export const INCREMENT_BAG_SIZE = 'INCREMENT_BAG_SIZE';
export const REMOVE_CLUB = 'REMOVE_CLUB';
export const RESET_CLUB = 'RESET_CLUB';
export const SET_BAG = 'SET_BAG';
export const SET_NEW_CLUB_VALUE = 'SET_NEW_CLUB_VALUE';
export const SET_USERNAME = 'SET_USERNAME';